### ISSUE TITLE
TODO by end of day May 2nd

### ISSUE THREAD

**Issue by amn41** [RasaHQ/conversational-ai-workshop-18#4]
- [x] write abstract (alan)
- [x] attention plots for 4 stories, including 2 where embedding gets it right and keras gets it wrong (vova)
- [x] add all the graphs and describe the results (akela)
- [x] hand-drawn architecture sketch (vova)
- [x] description of architecture including attention mechanism (vova)

not urgent but important:

- rename `keras` policy to what it is. It’s lstm with label tokenization, right vova?
- limitations section
- run experiments with standard policy without label featurization
- come up with a name for our architecture
